DROP DATABASE IF EXISTS GESCO_USERMANAGEMENT;

CREATE DATABASE IF NOT EXISTS GESCO_USERMANAGEMENT;

USE GESCO_USERMANAGEMENT;

DROP TABLE IF EXISTS AUDITORIA;
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS ROL_OFICINA;
DROP TABLE IF EXISTS ROL;
DROP TABLE IF EXISTS OFICINA;
DROP TABLE IF EXISTS FUENTE_DATOS;

CREATE TABLE IF NOT EXISTS AUDITORIA (
	USERNAME VARCHAR(50)  NOT NULL,
	FECHA	 TIMESTAMP	  NOT NULL,
	ACCION	 VARCHAR(300) NOT NULL,
	ROL		 VARCHAR(50)  NOT NULL
);

CREATE TABLE IF NOT EXISTS FUENTE_DATOS (
	URL 	 VARCHAR(200) NOT NULL PRIMARY KEY,
	SERVIDOR VARCHAR(30)  NOT NULL,
	PUERTO 	 INT 		  NOT NULL,
	USERNAME VARCHAR(50)  NOT NULL,
	PASSWORD VARCHAR(50)  NOT NULL
);

CREATE TABLE IF NOT EXISTS OFICINA (
	CODIGO 	  VARCHAR(20)  NOT NULL PRIMARY KEY,
	NOMBRE 	  VARCHAR(50)  NOT NULL,
	DIRECCION VARCHAR(300) NOT NULL,
	URL_DATOS VARCHAR(200),
	FOREIGN KEY (URL_DATOS) REFERENCES FUENTE_DATOS(URL)
);

CREATE TABLE IF NOT EXISTS ROL (
	CARGO 	  VARCHAR(50) NOT NULL PRIMARY KEY,
	ROL_GESCO VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROL_OFICINA (
	ROL_GESCO VARCHAR(50) NOT NULL,
	COD_OFIC  VARCHAR(20),
	PRIMARY KEY (ROL_GESCO, COD_OFIC),
--	FOREIGN KEY (ROL_GESCO) REFERENCES ROL(ROL_GESCO),
	FOREIGN KEY (COD_OFIC)	REFERENCES OFICINA(CODIGO)
);

CREATE TABLE IF NOT EXISTS EMPLEADO (
	DNI 	  VARCHAR(15)  NOT NULL PRIMARY KEY,
	NOMBRES   VARCHAR(30)  NOT NULL,
	APELLIDO1 VARCHAR(20)  NOT NULL,
	APELLIDO2 VARCHAR(20)  NOT NULL,
	DIRECCION VARCHAR(300) NOT NULL,
	TELEFONO  VARCHAR(15)  NOT NULL,
	FECHA_NAC TIMESTAMP,
	COD_OFIC  VARCHAR(20),
	FOREIGN KEY (COD_OFIC) REFERENCES OFICINA(CODIGO)
);